SELECT * FROM ARTICLE a;

SELECT * FROM ARTICLE a 
WHERE a.PRIX > 2;

SELECT * FROM  ARTICLE a 
WHERE a.PRIX BETWEEN 2 AND 6.25;

SELECT * FROM ARTICLE a 
WHERE a.PRIX NOT BETWEEN 2 AND 6.25
AND a.ID_FOU  = 1
ORDER BY a.PRIX DESC;

SELECT * FROM ARTICLE a 
WHERE a.ID_FOU = 1 OR a.id_fou  = 3;

SELECT * FROM ARTICLE a 
WHERE a.ID_FOU IN (1,3);

SELECT * FROM ARTICLE a 
WHERE a.ID_FOU NOT IN (1,3);

SELECT * FROM BON b 
WHERE b.DATE_CMDE BETWEEN '2019-02-01' AND '2019-04-30';



